version: '3.4'

services:

  minio-server:
    image: minio/minio:latest
    ports:
     - "9000:9000"
     - "9001:9001"
    environment:
     - MINIO_ROOT_USER=minioadmin
     - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
     - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  minio-data:

